name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: aws/environment-setup/parent-account/functions

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    # Upgrade npm so it works with our lockfile versions
    - name: Upgrade npm
      run: npm install -g npm@latest
    - name: Install node dependencies
      run: npm install -g aws-cdk

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install python dependencies
      run: pip install cfn-lint
      
    - run: npm ci
      working-directory: aws/utils
    - run: npm ci
    - run: npm run build
    - run: cp dummy.env .env
    - run: npm run test
    - run: npm run package
    # don't run the actual deploy in the CI, but run everything up to here to get the best idea of whether it works
