name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    # Upgrade npm so it works with our lockfile versions
    - name: Upgrade npm
      run: npm install -g npm@latest
    - name: Install node dependencies
      run: npm install -g aws-cdk
    - name: Set up environment
      run: mkdir cdk.tmp
      working-directory: aws/environment-setup
    - name: Set up test environment
      run: cp dummy.env .env
      working-directory: aws/environment-setup

    - run: npm ci
      working-directory: aws/utils
    - run: npm ci
      working-directory: aws/environment-setup
    - run: npm run testsynth
      working-directory: aws/environment-setup
    - run: npm run test
      working-directory: aws/environment-setup
    # don't run the actual deploy in the CI, but run everything up to here to get the best idea of whether it works
