name: CI

on: [push, pull_request]

env:
  npm_config_engine_strict: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Set up environment
      run: mkdir cdk.tmp
      working-directory: aws/environment-setup
    - name: Set up test environment
      run: cp dummy.env .env
      working-directory: aws/environment-setup

    - run: npm ci
      working-directory: aws/utils
    - run: npm run test
      working-directory: aws/utils

    - run: npm ci
      working-directory: aws/environment-setup
    - run: npm run testsynth
      working-directory: aws/environment-setup
    - run: npm run test
      working-directory: aws/environment-setup
    # don't run the actual deploy in the CI, but run everything up to here to get the best idea of whether it works

    # edge code

    - run: npm ci
      working-directory: edge/iot
    - run: npm run test
      working-directory: edge/iot
    - name: Set up environment for docker build
      run: mkdir example-container/app && cp -r *.js* node_modules example-container/app/
      working-directory: edge/iot
    - run: docker-compose build
      working-directory: edge/iot/example-container
