name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: aws/environment-setup/parent-account/functions

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: npm ci
    - run: npm run build
    - run: npm run test
    - run: npm run package
    # don't run the actual deploy in the CI, but run everything up to here to get the best idea of whether it works
